version: '3.4'

services:

  backend:
    build: ./backend
    ports :
      - 5000:5000
    volumes :
      - ./backend :/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    environment:
      POSTGRES_USER: userpd
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: dbesiee

  frontend:
    build: ./front
    command: npm start
    volumes:
      - node_module:/app/node_modules
      - ./front:/app
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

  db:
    image: postgres
    ports :
      - 5432:5432
    environment:
      POSTGRES_USER: userpd
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: dbesiee
    volumes : 
      - db-todo-service:/var/lib/postgresql/data

volumes :
  db-todo-service:
  node_module: